server:
  port: 7070
  servlet:
    context-path: /webapp

spring:
  application:
    name: TestNTT

  config:
    activate:
      on-profile: local
  datasource:
    url:  jdbc:postgresql://localhost:54321/organizations_db
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

mapstruct:
  defaultComponentModel: spring